import { getTranscriptContent } from "../Llm.js";
import { matchCoins } from "../LoadCoinsData.js";
import { convertTimestampToSeconds, validateTimestamps } from "../utils.js";
import { transcript } from "./test2.js";

const typicalData = {
  projects: [
    {
      valid: true,
      action: "NO ACTION",
      rpoints: 9,
      category: ["Cryptocurrency", "Investment"],
      found_in: "screenshot",
      marketcap: "large",
      Timestamps: [
        "00:00:11",
        "00:00:12",
        "00:09:59",
        "00:10:00",
        "00:09:19",
        "00:09:20",
        "00:10:47",
        "00:10:48",
        "00:11:13",
        "00:11:14",
      ],
      total_count: 3,
      possible_match: "none",
      coin_or_project: "Bitcoin",
    },
    {
      valid: true,
      action: "NO ACTION",
      rpoints: 8,
      category: ["Layer 1", "Smart Contracts"],
      found_in: "screenshot",
      marketcap: "medium",
      Timestamps: ["00:00:52", "00:00:53", "00:11:58", "00:11:59"],
      total_count: 3,
      possible_match: "none",
      coin_or_project: "NEAR Protocol",
    },
    {
      valid: true,
      action: "NO ACTION",
      rpoints: 7,
      category: ["Meme coins"],
      found_in: "screenshot",
      marketcap: "micro",
      Timestamps: [
        "00:00:52",
        "00:00:53",
        "00:01:11",
        "00:01:12",
        "00:05:07",
        "00:05:08",
      ],
      total_count: 3,
      possible_match: "none",
      coin_or_project: "Peanut the Squirrel",
    },
    {
      valid: true,
      action: "NO ACTION",
      rpoints: 6,
      category: ["Layer 1", "Smart Contracts"],
      found_in: "screenshot",
      marketcap: "large",
      Timestamps: [
        "00:31:37",
        "00:31:38",
        "00:31:30",
        "00:31:31",
        "00:31:20",
        "00:31:21",
        "00:31:40",
        "00:31:41",
        "00:02:38",
        "00:02:39",
      ],
      total_count: 3,
      possible_match: "none",
      coin_or_project: "Cardano",
    },
    {
      valid: true,
      action: "NO ACTION",
      rpoints: 8,
      category: ["Gaming", "Infrastructure"],
      found_in: "screenshot",
      marketcap: "small",
      Timestamps: [
        "00:35:32",
        "00:35:33",
        "00:01:47",
        "00:01:48",
        "00:38:57",
        "00:38:58",
      ],
      total_count: 3,
      possible_match: "none",
      coin_or_project: "SuperVerse",
    },
    {
      valid: true,
      action: "NO ACTION",
      rpoints: 8,
      category: ["AI", "Infrastructure"],
      found_in: "screenshot",
      marketcap: "micro",
      Timestamps: [
        "00:01:47",
        "00:01:48",
        "00:38:44",
        "00:38:45",
        "00:42:29",
        "00:42:30",
      ],
      total_count: 3,
      possible_match: "none",
      coin_or_project: "Destra Network",
    },
    {
      valid: false,
      action: "DELETE",
      rpoints: 7,
      category: ["Gaming"],
      found_in: "none",
      marketcap: "medium",
      Timestamps: ["00:01:53", "00:01:54", "00:31:59", "00:32:00"],
      total_count: 3,
      possible_match: "none",
      coin_or_project: "Axie Infinity",
    },
    {
      valid: true,
      action: "NO ACTION",
      rpoints: 7,
      category: ["AI"],
      found_in: "screenshot",
      marketcap: "micro",
      Timestamps: [
        "00:40:30",
        "00:40:31",
        "00:01:53",
        "00:01:54",
        "00:37:53",
        "00:37:54",
        "00:38:22",
        "00:38:23",
      ],
      total_count: 3,
      possible_match: "none",
      coin_or_project: "PaLM AI",
    },
    {
      valid: true,
      action: "NO ACTION",
      rpoints: 7,
      category: ["Video Streaming", "AI"],
      found_in: "transcript",
      marketcap: "medium",
      Timestamps: [
        "00:02:00",
        "00:02:01",
        "00:33:14",
        "00:33:15",
        "00:33:26",
        "00:33:27",
      ],
      total_count: 3,
      possible_match: "none",
      coin_or_project: "Theta Network",
    },
    {
      valid: true,
      action: "NO ACTION",
      rpoints: 9,
      category: ["Layer 1", "DeFi"],
      found_in: "screenshot",
      marketcap: "large",
      Timestamps: [
        "00:12:49",
        "00:12:50",
        "00:29:30",
        "00:29:31",
        "00:20:27",
        "00:20:28",
        "00:20:32",
        "00:20:33",
        "00:28:14",
        "00:28:15",
      ],
      total_count: 3,
      possible_match: "none",
      coin_or_project: "Solana",
    },
    {
      valid: true,
      action: "NO ACTION",
      rpoints: 8,
      category: ["Layer 1", "Smart Contracts"],
      found_in: "screenshot",
      marketcap: "medium",
      Timestamps: [
        "00:11:40",
        "00:11:41",
        "00:11:45",
        "00:11:46",
        "00:11:47",
        "00:11:48",
      ],
      total_count: 3,
      possible_match: "none",
      coin_or_project: "Sui",
    },
    {
      valid: true,
      action: "NO ACTION",
      rpoints: 7,
      category: ["Layer 1"],
      found_in: "transcript",
      marketcap: "medium",
      Timestamps: [
        "00:23:46",
        "00:23:47",
        "00:35:21",
        "00:35:22",
        "00:18:15",
        "00:18:16",
        "00:35:10",
        "00:35:11",
        "00:22:56",
        "00:22:57",
      ],
      total_count: 3,
      possible_match: "none",
      coin_or_project: "Core",
    },
    {
      valid: true,
      action: "NO ACTION",
      rpoints: 7,
      category: ["Oracle"],
      found_in: "screenshot",
      marketcap: "large",
      Timestamps: [
        "00:32:24",
        "00:32:25",
        "00:32:26",
        "00:32:29",
        "00:32:30",
        "00:32:31",
        "00:32:32",
      ],
      total_count: 3,
      possible_match: "none",
      coin_or_project: "Chainlink",
    },
    {
      valid: false,
      action: "DELETE",
      rpoints: 4,
      category: ["Exchange Token"],
      found_in: "none",
      marketcap: "micro",
      Timestamps: ["00:12:51", "00:12:52"],
      total_count: 3,
      possible_match: "none",
      coin_or_project: "FTX Token",
    },
    {
      valid: true,
      action: "NO ACTION",
      rpoints: 8,
      category: ["AI", "Gaming"],
      found_in: "screenshot",
      marketcap: "micro",
      Timestamps: [
        "00:39:29",
        "00:39:30",
        "00:41:12",
        "00:41:13",
        "00:37:37",
        "00:37:38",
      ],
      total_count: 3,
      possible_match: "none",
      coin_or_project: "Echelon Prime",
    },
    {
      valid: false,
      action: "DELETE",
      rpoints: 8,
      category: ["Layer 2"],
      found_in: "none",
      marketcap: "medium",
      Timestamps: ["00:38:02", "00:38:03", "00:38:06", "00:38:07"],
      total_count: 3,
      possible_match: "none",
      coin_or_project: "ZKsync",
    },
    {
      valid: true,
      action: "NO ACTION",
      rpoints: 8,
      category: ["AI"],
      found_in: "screenshot",
      marketcap: "micro",
      Timestamps: [
        "00:40:38",
        "00:40:39",
        "00:40:02",
        "00:40:03",
        "00:40:19",
        "00:40:20",
        "00:41:15",
        "00:41:16",
        "00:05:40",
        "00:05:41",
      ],
      total_count: 3,
      possible_match: "none",
      coin_or_project: "Node AI",
    },
    {
      valid: true,
      action: "NO ACTION",
      rpoints: 8,
      category: ["AI"],
      found_in: "screenshot",
      marketcap: "micro",
      Timestamps: ["00:40:11", "00:40:12", "00:38:13", "00:38:14"],
      total_count: 3,
      possible_match: "none",
      coin_or_project: "Neural AI",
    },
    {
      valid: true,
      action: "NO ACTION",
      rpoints: 8,
      category: ["AI"],
      found_in: "screenshot",
      marketcap: "micro",
      Timestamps: ["00:40:26", "00:40:27", "00:38:13", "00:38:14"],
      total_count: 3,
      possible_match: "none",
      coin_or_project: "Hash AI",
    },
    {
      valid: true,
      action: "NO ACTION",
      rpoints: 8,
      category: ["Gaming"],
      found_in: "screenshot",
      marketcap: "medium",
      Timestamps: ["00:35:19", "00:35:20"],
      total_count: 3,
      possible_match: "none",
      coin_or_project: "Immutable",
    },
    {
      valid: true,
      action: "NO ACTION",
      rpoints: 8,
      category: ["Gaming"],
      found_in: "screenshot",
      marketcap: "micro",
      Timestamps: [
        "00:35:19",
        "00:35:20",
        "00:33:19",
        "00:33:20",
        "00:10:33",
        "00:10:34",
        "00:02:07",
        "00:02:08",
        "00:16:52",
        "00:16:53",
      ],
      total_count: 3,
      possible_match: "none",
      coin_or_project: "Beam",
    },
    {
      valid: true,
      action: "NO ACTION",
      rpoints: 8,
      category: ["Gaming"],
      found_in: "screenshot",
      marketcap: "medium",
      Timestamps: [
        "00:04:17",
        "00:04:18",
        "00:04:31",
        "00:04:32",
        "00:06:46",
        "00:06:47",
        "00:35:38",
        "00:35:39",
        "00:35:33",
        "00:35:34",
      ],
      total_count: 3,
      possible_match: "none",
      coin_or_project: "Ronin",
    },
    {
      valid: false,
      action: "DELETE",
      rpoints: 8,
      category: ["Gaming", "Launchpad"],
      found_in: "none",
      marketcap: "small",
      Timestamps: ["00:39:33", "00:39:34"],
      total_count: 3,
      possible_match: "none",
      coin_or_project: "Seedify.fund",
    },
    {
      valid: false,
      action: "DELETE",
      rpoints: 8,
      category: ["Gaming"],
      found_in: "none",
      marketcap: "micro",
      Timestamps: ["00:39:45", "00:39:46"],
      total_count: 3,
      possible_match: "none",
      coin_or_project: "Myria",
    },
    {
      valid: false,
      action: "DELETE",
      rpoints: 7,
      category: ["Gaming", "Scaling"],
      found_in: "none",
      marketcap: "small",
      Timestamps: ["00:39:53", "00:39:54"],
      total_count: 3,
      possible_match: "none",
      coin_or_project: "Celer Network",
    },
    {
      valid: false,
      action: "DELETE",
      rpoints: 8,
      category: ["Gaming"],
      found_in: "none",
      marketcap: "micro",
      Timestamps: ["00:40:01", "00:40:02"],
      total_count: 3,
      possible_match: "none",
      coin_or_project: "Xterio",
    },
    {
      valid: false,
      action: "DELETE",
      rpoints: 8,
      category: ["Gaming"],
      found_in: "none",
      marketcap: "micro",
      Timestamps: [
        "00:38:48",
        "00:38:49",
        "00:41:08",
        "00:41:09",
        "00:38:24",
        "00:38:25",
        "00:40:59",
        "00:41:00",
      ],
      total_count: 3,
      possible_match: "none",
      coin_or_project: "KARRAT",
    },
    {
      valid: false,
      action: "DELETE",
      rpoints: 8,
      category: ["Gaming"],
      found_in: "none",
      marketcap: "micro",
      Timestamps: ["00:41:04", "00:41:05"],
      total_count: 3,
      possible_match: "none",
      coin_or_project: "Altura",
    },
    {
      valid: false,
      action: "DELETE",
      rpoints: 7,
      category: ["Gaming"],
      found_in: "none",
      marketcap: "small",
      Timestamps: ["00:41:59", "00:42:00"],
      total_count: 3,
      possible_match: "none",
      coin_or_project: "Illuvium",
    },
  ],
  total_count: 87,
  total_rpoints: 229,
};

//getTranscriptContent("https://www.youtube.com/watch?v=JgjGJTrL3hY");
//validateTimestamps(typicalData, transcript);
//const data = await matchCoins(typicalData);
//console.log("Matched data: " + data);
